#  Module 2 Intro to NumPy



In [84]:
import numpy as np

In [4]:
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### You can use NumPy Array to allow multiplying one matrice to the other with no TypeError



In [7]:
a_np = np.array(a)

In [14]:
print(a_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(type(a_np))

<class 'numpy.ndarray'>


In [20]:
b = [[10,11,12],[13,14,15],[16,17,18]]

In [21]:
b_np = np.array(b)

In [22]:
x = a * b # cant multiply matrice on matrice

TypeError: can't multiply sequence by non-int of type 'list'

In [24]:
y = a_np * b_np # numpy, on contrary, allows multiplying matrices in that simple way
print(y)
print(type(y))

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
<class 'numpy.ndarray'>


In [28]:
z = np.zeros((2,5)) # this function creates a matrice of zeroes with 2 X 5 dimensions

In [29]:
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
k = np.ones((4,7)) # function creates matrice made of ones with 4 lists and 7 elements in each list

In [31]:
print(k)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [32]:
l = np.eye(7) # function creates an identity matrix with 7 lists and 7 elements in each
print(l)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [76]:
k = np.full((4,4),155)
k

array([[155, 155, 155, 155],
       [155, 155, 155, 155],
       [155, 155, 155, 155],
       [155, 155, 155, 155]])

### Use NumPy arange to iterate through numbers with float step 



In [33]:
for i in range(10,20,0.5): # Not using NumPy does not allow to use float step value
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
for i in np.arange(10,20,0.5):
    print(i)

10.0
10.5
11.0
11.5
12.0
12.5
13.0
13.5
14.0
14.5
15.0
15.5
16.0
16.5
17.0
17.5
18.0
18.5
19.0
19.5


### Use NumPy .ravel() method to convert an array to a contiguous flattened array  
### Use .transpose() method or .T to transpose an array  


In [44]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a_np = np.array(a)

a_np.ravel() # use .ravel() to convert array to a contiguous flattened array


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a_np.T # use .transpose() or .T to transpose array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## We can do the following math operations with matrices A and B of the same size: 
### multiply, divide, add, extract or raise to a power  
### the resulting matrice will be the same size as A and B

In [49]:
m = np.array([[1,2],[3,4]])
n = np.array([[1,2],[3,4]])

print(m)
print(n)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [51]:
print('m * n\n', m*n) # multiplying

m * n
 [[ 1  4]
 [ 9 16]]


In [52]:
print('m - n\n', m-n) # extraction

m - n
 [[0 0]
 [0 0]]


In [53]:
print('m + n\n', m+n) # addition

m + n
 [[2 4]
 [6 8]]


In [54]:
print('m / n\n', m/n) # division

m / n
 [[1. 1.]
 [1. 1.]]


In [56]:
print('m ** n\n',m**n) # raising to a power

m ** n
 [[  1   4]
 [ 27 256]]


In [58]:
print('2m:\n',m * 2) # we can do operations with matrices and numbers: multiply, divide, or raise to a power

2m:
 [[2 4]
 [6 8]]


### The definition of "nan" 
#### nan is not equal to 0 or empty string ' ', it does not even equal to itself 

In [60]:
nan = np.nan

if nan == 0:
    print('nan equals to 0')
elif nan == '':
    print('nan equals to \'\'')
elif nan == np.nan:
    print('nan equals to itself')
else:
    print('nan neither equals to 0 or empty string nor to itself')

nan neither equals to 0 or empty string nor to itself


In [62]:
print(nan)

print(type(nan))

nan
<class 'float'>


## How to generate a random number
### np.random.rand(x, y) allows to generate an array with random numbers from 0 to 1 with x * y dimensions

In [3]:
o = np.random.rand(4,4) # initialize 4*4 array with elements ranging from 0 to 1

print(o)

[[0.91924202 0.44539769 0.40972661 0.12866464]
 [0.93307411 0.82716256 0.07295913 0.03557477]
 [0.54650567 0.88128586 0.06933244 0.20561629]
 [0.96837417 0.84908248 0.00863538 0.95260241]]


### np.random.randit(low = x, high = y, size = z) allows to generate an array with random numbers limited by low and
### high values and dimensions defined by size (a, b)

In [4]:
o = np.random.randint(low = 1, high = 50, size = (4,4))

print(o)

[[31 27 49 14]
 [39 19 28 10]
 [ 1  9 28 21]
 [42 30 31 15]]


In [51]:
# Create daily sales array with purchase sum in columns and daily sales in rows. All cheques contain 8 items, overall daily
# sales are 15000 items. The most expensive item costs 5000 RUB.

daily_sales = np.random.randint(low = 1, high = 5000, size = (15000,8))
print(daily_sales)


[[2488 4558  490 ... 1956 1440 1667]
 [1088 4154  231 ... 2137 3694 2865]
 [2026 4414 2343 ... 2788 2424 3138]
 ...
 [4821  164 4853 ... 4728  751  161]
 [1645 3219 3053 ... 2746 4810 1093]
 [ 439  382 3405 ... 2074 4276 1585]]


In [7]:
# calculate min value using np.min() function
np.min(daily_sales)

# calculate max value using np.max() function
np.max(daily_sales)

4999

In [10]:
# calculate mean value of entire array using np.mean() function
np.mean(daily_sales)

2494.9939083333334

In [11]:
# calculate sum value using np.sum() function
np.sum(daily_sales)

299399269

In [12]:
# calculate median value using np.median() function
np.median(daily_sales)

2490.0

## To perform mathematical functions within one row or column, we need to define axis (0 or 1) after comma

In [53]:
np.min(daily_sales, axis = 0) # use 0 after comma to work with columns or 1 to work with rows

array([1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
np.min(daily_sales, axis = 1) # use 0 after comma to work with columns or 1 to work with rows

array([ 490,  231, 1200, ...,  161, 1093,  382])

### Task 1



In [18]:
list_1 = [] # initialize empty lists
list_2 = []

for i in range(1,101): # iterate through range 1-100
    list_1.append(i) # append each value to empty lists
    list_2.append(i)
    
np_list_1 = np.array(list_1)
np_list_2 = np.array(list_2)

result = np_list_1 * np_list_2

print(result[17])

324


### Task 2

In [29]:
default_list = [] # initialize an empty list

o = np.eye(5) # initialize an identity matrix with 5 lists and 5 elements in each

list_1 = o.ravel() # use .ravel() to convert array to a contiguous flattened array

for i in np.arange(25,12.5,-0.5):
    default_list.append(i)

list_2 = np.array(default_list)

print('default_list:',default_list,'\ndefault list type:',type(default_list),'\n')
      
print('NumPy list_2:',list_2,'\nNumPy list_2 type:',type(list_2))

default_list: [25.0, 24.5, 24.0, 23.5, 23.0, 22.5, 22.0, 21.5, 21.0, 20.5, 20.0, 19.5, 19.0, 18.5, 18.0, 17.5, 17.0, 16.5, 16.0, 15.5, 15.0, 14.5, 14.0, 13.5, 13.0] 
default list type: <class 'list'> 

NumPy list_2: [25.  24.5 24.  23.5 23.  22.5 22.  21.5 21.  20.5 20.  19.5 19.  18.5
 18.  17.5 17.  16.5 16.  15.5 15.  14.5 14.  13.5 13. ] 
NumPy list_2 type: <class 'numpy.ndarray'>


In [30]:
result = list_1 * list_2

print(result[9])

0.0


### Task 3

In [31]:
matrix_1 = [[1,2],[3,9]]
matrix_2 = np.array(matrix_1)

T_matrix_2 = matrix_2.T

result = matrix_2 * T_matrix_2

print(np.sum(result))

94


### Exercises from Youtube Video "Intro to NumPy"
https://www.youtube.com/watch?v=QUT1VHiLmmI

In [85]:
a = [[1,2,3],[4,5,6],[7,8,9]]

a_np = np.array(a, dtype = 'int16') 

In [24]:
# Get shape
a_np.shape

(3, 3)

In [25]:
# Get dimensions
a_np.ndim

2

In [31]:
# get type
a_np.dtype.name

'int16'

In [93]:
# ensure that an array is of a specific type

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.issubdtype(a, np.integer)

TypeError: data type not understood

In [101]:
# test sandbox

np.issubdtype('a', np.floating)

False

In [27]:
# get size (reveals how much memory NumPy array takes)
a_np.size

9

In [29]:
# get itemsize
a_np.itemsize

2

In [30]:
# get data
a_np.data

In [63]:
# get total size
a_np.size

9

In [64]:
# get number of bytes
a_np.nbytes

18

In [34]:
# use linspace instead of arange to create an array

np.linspace(0,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

### Elementwise multiplication * and matrix product (@ or dot) in NumPy 

In [43]:
a = np.linspace(0,2,10)
b = np.arange(10)


dtype('int64')

In [44]:
a*b # elementwise product

array([ 0.        ,  0.22222222,  0.88888889,  2.        ,  3.55555556,
        5.55555556,  8.        , 10.88888889, 14.22222222, 18.        ])

In [45]:
a @ b # matrix product

63.33333333333333

In [47]:
a.dot(b) # another matrix product

63.33333333333333

AttributeError: module 'numpy.random' has no attribute 'default_rng'

### Reshape function


In [59]:
a = np.floor(10*np.random.rand(3,4)) # I ain't even got what I've defined there!!!

In [61]:
a.reshape(6,-1) # reshape with other dimensions automatically calculated

array([[6., 2.],
       [4., 7.],
       [6., 2.],
       [5., 2.],
       [7., 4.],
       [2., 1.]])

## Access/change specific elements, rows, columns, etc

In [65]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [66]:
# Get a specific element [r, c]

a[1,5]

13

In [67]:
# Get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [68]:
# Get a specific column

a[:, 2]

array([ 3, 10])

In [73]:
# Getting fancy [startindex:endindex:stepsize]

a[1,1:6:2]

array([ 9, 11, 13])

In [74]:
# replace specific element in an array

a[1,5] = 23

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 23, 14]])

In [ ]:
# To get a specific element in a 3-d array, work outside in
